development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: teachers_pet_upgraded
  pool: 5
  username: root
  password: 
  socket: '/opt/boxen/data/mysql/socket'
  port: 13306
test: &test
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: teachers_pet_upgraded
  pool: 5
  username: root
  password: 
  socket: '/opt/boxen/data/mysql/socket'
  port: 13306

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: teachers_pet_upgraded
  pool: 5
  username: root
  password: 

cucumber:
  <<: *test